name: Wandduk
options:
  bundleIdPrefix: com.raqoon886
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    GENERATE_INFOPLIST_FILE: YES

targets:
  Wandduk:
    type: application
    platform: iOS
    sources:
      - path: Wandduk
        excludes:
          - "**/*.xcassets"
      - path: Wandduk/Assets.xcassets
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSCameraUsageDescription: "맛있는 음식 사진을 기록하기 위해 카메라 접근이 필요합니다."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "음식 사진을 저장하기 위해 사진 라이브러리 접근이 필요합니다."
        PRODUCT_BUNDLE_IDENTIFIER: com.raqoon886.wandduk
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

schemes:
  Wandduk:
    build:
      targets:
        Wandduk: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
